"""initial schema

Revision ID: 2b7bf3181178
Revises: 
Create Date: 2026-04-17 20:24:09.844446
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2b7bf3181178'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_sessions',
    sa.Column('jti', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('performances',
    sa.Column('performance_id', sa.String(length=26), nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('author_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('moderation_ingress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('moderation_egress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('performance_id')
    )
    op.create_index('idx_perf_author', 'performances', ['author_ip_hash', 'created_at'], unique=False)
    op.create_index('idx_perf_created', 'performances', ['created_at'], unique=False)
    op.create_table('visitors',
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('msg_count', sa.Integer(), nullable=False),
    sa.Column('ban_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ip_hash')
    )
    op.create_table('moderation_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('performance_id', sa.String(length=26), nullable=True),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('detector', sa.String(length=32), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performance_id'], ['performances.performance_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderation_events')
    op.drop_table('visitors')
    op.drop_index('idx_perf_created', table_name='performances')
    op.drop_index('idx_perf_author', table_name='performances')
    op.drop_table('performances')
    op.drop_table('operator_sessions')
    # ### end Alembic commands ###
